apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telemetry-stack.fullname" . }}-grafana-datasource
  labels:
    app: grafana
    {{- include "telemetry-stack.labels" . | nindent 4 }}
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-service:9090
      uid: prometheus
      isDefault: true
      editable: false