{{- if .Values.influxdb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
    chart: {{ include "telemetry-stack.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.influxdb.service.type }}
  selector:
    app: influxdb
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.influxdb.service.port }}
    targetPort: {{ .Values.influxdb.service.port }}
{{- end }}