apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: collector:latest
        imagePullPolicy: Never
        env:
        - name: INFLUXDB_URL
          value: http://influxdb:8086
        - name: INFLUXDB_TOKEN
          value: supersecrettoken
        - name: INFLUXDB_ORG
          value: telemetryorg
        - name: INFLUXDB_BUCKET
          value: telem_bucket
---
apiVersion: v1
kind: Service
metadata:
  name: collector
spec:
  selector:
    app: collector
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
