apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msg-queue
  template:
    metadata:
      labels:
        app: msg-queue
    spec:
      containers:
      - name: msg-queue
        image: msg-queue:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: BROKER_INDEX
          value: "0"
        - name: BROKER_COUNT
          value: "1"
        - name: TOPICS
          value: "telemetry:4,events:8,orders:4,default:8"
        volumeMounts:
        - name: msg-queue-storage
          mountPath: /root/data
      volumes:
      - name: msg-queue-storage
        persistentVolumeClaim:
          claimName: msg-queue-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: msg-queue
spec:
  selector:
    app: msg-queue
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: msg-queue-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi