apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer
  template:
    metadata:
      labels:
        app: streamer
    spec:
      containers:
      - name: streamer
        image: streamer:latest
        imagePullPolicy: Never
        env:
        - name: CSV_PATH
          value: /data/dcgm_metrics_20250718_134233.csv
        - name: CSV_DELAY_MS
          value: "1000"
        volumeMounts:
        - name: csv-data
          mountPath: /data
      volumes:
      - name: csv-data
        hostPath:
          path: /localdata/peaswaran/telemtry
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: streamer
spec:
  selector:
    app: streamer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
