apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer
  template:
    metadata:
      labels:
        app: streamer
    spec:
      containers:
      - name: streamer
        image: streamer:latest
        imagePullPolicy: Never
        env:
        - name: CSV_PATH
          value: /data/dcgm_metrics_20250718_134233.csv
        - name: CSV_DELAY_MS
          value: "1000"
        - name: USE_HTTP_QUEUE
          value: "true"
        - name: MSG_QUEUE_ADDR
          value: "http://msg-queue:8080"
        - name: MSG_QUEUE_TOPIC
          value: "telemetry"
        - name: MSG_QUEUE_GROUP
          value: "telemetry_group"
        - name: MSG_QUEUE_PRODUCER_NAME
          value: "streamer"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: csv-data
          mountPath: /data
      volumes:
      - name: csv-data
        hostPath:
          path: /run/desktop/mnt/host/c/Users/peaswaran/telemetry_Punitha
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: streamer
spec:
  selector:
    app: streamer
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
